
spring:
  application:
    name: oxidator
  data:
    mongodb:
      uri: "mongodb://51.222.52.204:27017/"
      database: "liftgate"
  web:
    resources:
      add-mappings: false
server:
  error:
    whitelabel:
      enabled: false
oxidator:
  baseURL: "http://localhost:8080"
  builtbybit:
    secret: "CHANGE ME"
  discord:
    guild: "CHANGE ME"
    token: "CHANGE ME"
  tebex:
    category: "Software"
    apikey: "CHANGE ME"
logging:
  level:
    root: info
management:
  health:
    mongo:
      enabled: false
